version: "3.8"
services:
  server:
    container_name: cgstav
    build:
      context: ./server
      dockerfile: Dockerfile
    image: gstav
    ports:
      - "5000:5000"
    volumes:
      - ./server:/server
    env_file: .env

  db:
    container_name: cgstav-db
    build:
      context: ./db
      dockerfile: Dockerfile
    image: gstav-db
    ports:
      - "27017:27017"
    volumes:
      - ./db/data:/data/db
    command: mongod --quiet --logpath /dev/null
