version: "3.8"
services:
  server:
    container_name: cgstav
    build:
      context: ./server
      dockerfile: Dockerfile
    image: gstav
    ports:
      - "${IP}:5000:5000"
    volumes:
      - ./server:/server

  db:
    container_name: cgstav-db
    build:
      context: ./db
      dockerfile: Dockerfile
    image: gstav-db
    ports:
      - "27017:27017"
    volumes:
      - ./db/config.js:/docker-entrypoint-initdb.d/config.js
      - ./db/data:/data/db
    environment:
      MONGO_INITDB_DATABASE: gstavmongo
